Feature/server side render actions trade
eReuse/devicehub-teal pull request #203
Opened 2022-02-21 12:25 UTC by cayop

## Create trade
To make a trade it is necessary to make a temporary lot and press the tag Lot -> add supplier or receive.
* When a trade is made you can not ask for confirmation:
In this case it is necessary to enter a code. An automatic trade will be made. This means that one phantom account is created with the code and the id of the user who makes the trade. 
Then the device will be transferred to this new user. This is the current behaviour but we have to check that usody wants to keep this behaviour.

* The second case is when confirmation is needed. This implies that there have to be two users of the system that exist and one of them has to be the one who makes the trade.

It is not necessary to select device when making a trade because it affects all devices in the lot, whether they are selected or not.

## create document
When we have a lot with trade, then we can add documents related to this trade.
To achieve this we have to go to a lot with trade, then go to the tag Lot -> Add new document

When we have added a document we can see a top tag in the batch where we can select a list of devices, (activated by default) and a list of documents with the documents attached to the trade

2022-02-22 10:11 UTC, slamora requested changes

2022-02-22 11:05 UTC, slamora approved these changes

2022-02-22 11:11 UTC, slamora commented
Code review done. Wating for test E2E of @dfranquesa

2022-02-28 09:18 UTC, merged

2022-03-01 08:57 UTC, dfranquesa commented
**List of test**

Test 1 - Trade to supplier - 2 devices type computer - case 1 without confirmation, **RESULT: NOT Passed [#2840](https://tree.taiga.io/project/usody/task/2841)**

Test 5 - Trade to supplier - 2 devices type computer - case 2 with confirmation, **RESULT: NOT Passed [#2841](https://tree.taiga.io/project/usody/task/2841)**


2840 Test 1 - Trade to supplier - 2 devices type computer - case 1 without confirmation

In user1@dhub.com

supplier: user@dhub.com  
with confirmation

Process: 

I select with confirmation and I put a supplier (user@dhub.com).

Result:

Appears an incoming lot in user1@dhub.com? YES, Passed
Appears an outgoing lot in user@dhub.com? NO, NOT Passed
It seems that works because action is “created successfully” but do not appear an outgoing lot in user@dhub.com, see image.

Process: 

I select without a confirmation and I put a code but not works, see image.

Result:

Error “Object has no attribute code”., NOT Passed


2841 Test 5 - Trade to supplier - 2 devices type computer - case 2 with confirmation

Appears an incoming lot in user1@dhub.com? YES, Passed
Appears an outgoing lot in user@dhub.com? NO, NOT Passed