Add reactive lots list
eReuse/devicehub-teal pull request #218
Opened 2022-04-07 11:37 UTC by RubenPX

TODOS:
- [ ] [ISSUE] User token not working `{{ current_user.token }}`, Search alternative
- [ ] Remove unnecesary views
- [ ] Add select all button

2022-04-07 11:38 UTC, RubenPX commented on ereuse_devicehub/templates/inventory/device_list.html
> +    Auth_Token: "Basic ZDc5YjQyOGItZTJjMy00NDA0LThhODItNzJjMTNmOWNkYmNjOg==", // {{ current_user.token }}
`{{ current_user.token }}`

This variable returns user id instead user token

2022-04-07 12:15 UTC, RubenPX commented
https://github.com/eReuse/devicehub-teal/pull/218/commits/184d22ac816dd9be908b5c46294bb72d52670610

Token encoded to base64 but not working

2022-04-11 11:55 UTC, RubenPX commented on ereuse_devicehub/templates/ereuse_devicehub/base_site.html
> +  const API_URLS = {
WARNING: This pull request maybe has a conflict with https://github.com/eReuse/devicehub-teal/pull/219

2022-04-11 14:32 UTC, slamora requested changes
Thanks @RubenPX almost it's working properly but after adding or removing devices of the current lot number of entries should be updated (see attached screen):

Only 1 entry exists but still remains old value "1 of 2".

- [ ] Update number of existing entries on table footer
![image](https://user-images.githubusercontent.com/4057718/162761213-19eb9417-850b-4a8f-8c41-19d55354736b.png)

- [ ] UX Make lot name clickable (instead of only related checkbox)
![image](https://user-images.githubusercontent.com/4057718/162762132-2add441a-a441-439b-8b80-73e7893a7928.png)

2022-04-11 14:32 UTC, slamora commented on ereuse_devicehub/static/js/main_inventory.js
> +         * @param {*} ev event (Should be a checkbos type)
```suggestion
         * @param {*} ev event (Should be a checkbox type)
```

2022-04-11 14:32 UTC, slamora commented on ereuse_devicehub/static/js/main_inventory.js
> + * Añade reactividad al botón de lotes
```suggestion
 * Reactive lots button
```

2022-04-12 11:48 UTC, slamora commented
Superseeded by #220

2022-04-12 11:48 UTC, closed without merging