FEATURE: Search lots and devices
eReuse/devicehub-teal pull request #219
Opened 2022-04-11 11:49 UTC by RubenPX

This feature implements a functionality search on the top search bar

Search terms:
- By device id
- By lot name

TDODS:
- [X] Research API in docs
- [X] Design basic search design
- [X] Add search by device ID and limit by 4 results
- [X] Add search by lot name and limit by 4 results
- [X] Add delay 2 seconds when write (This avoid api spam)
- [X] Testing

2022-04-11 11:55 UTC, RubenPX commented on ereuse_devicehub/templates/ereuse_devicehub/base_site.html
> +  const API_URLS = {
> WARNING: This pull request maybe has a conflict with https://github.com/eReuse/devicehub-teal/pull/218

2022-04-11 14:45 UTC, slamora requested changes
Works like a charm! Thanks @RubenPX . Just a minor detail:
An empty square is showed when focus is active on search box. Maybe can we hidde it until some results are shown?
![image](https://user-images.githubusercontent.com/4057718/162764772-78418328-68b4-4e56-adce-2b507d49c4d0.png)

2022-04-12 07:42 UTC, RubenPX commented
- [X] https://github.com/eReuse/devicehub-teal/pull/219#pullrequestreview-938125744 --> https://github.com/eReuse/devicehub-teal/pull/219/commits/34da3599f3d144ee44e0f423592ceac267f96c70
- [ ] Show "Nothing found" when results are empty

2022-04-12 11:01 UTC, slamora approved these changes

2022-04-12 11:01 UTC, merged